pipeline {
    agent any
    stages {
        stage('Build') { 
        steps {
        sh'cd Back2End'
               bat '''
               cd Bac2End
               mvn -B -DskipTests clean package'''
            }
        }
    }
}