pipeline {
    agent any
    stages {
        stage('Build') { 
        steps {
               bat '''
               cd Bac2End
               mvn -B -DskipTests clean package
               '''
            }
        }
         stage('Test') { 
            steps {
                bat'''
               cd Bac2End 
                mvn test
               '''  
            }
            }
            
            
        stage('Deliver') {
            steps {
            bat'''
            cd ../../..
                ./jenkins/scripts/deliver.sh
               '''
                
            }
        }    
            
        
    }
}